apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: libertyform-spring
  name: libertyform-spring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: libertyform-spring
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: libertyform-spring
    spec:
      containers:
      - name: libertyform-spring
        image: forcetlight/libertyform-spring:76
        ports:
          - containerPort: 8080
