apiVersion: v1
kind: Service
metadata:
  labels:
    app: libertyform-flask
  name: libertyform-flask
spec:
  type: LoadBalancer
  selector:
    app: libertyform-flask
  ports:
    - port: 5000
      targetPort: 5000
