apiVersion: v1
kind: Service
metadata:
  labels:
    app: libertyform-react
  name: libertyform-react
spec:
  type: LoadBalancer
  selector:
    app: libertyform-react
  ports:
    - port: 3000
      targetPort: 3000
