apiVersion: v1
kind: Service
metadata:
  labels:
    app: libertyform-springk8s
  name: libertyform-spring
spec:
  type: LoadBalancer
  selector:
    app: libertyform-spring
  ports:
    - port: 8080
      targetPort: 8080
